### PR TITLE
Add binary/ImageData testing helper and example

### PR DESCRIPTION
**Pull request by s-ol**
Photoshop won't run on my Linux installation currently,
so I had to reuse the test data from the unicode example.

It would be great if you could add a (few?) test(s) that check things you believe are important/error prone (like having a non-grayscale image to check that the channels end up in the right order, maybe testing 1-channel .psd's (if that's even supported rn) etc.).

Oh, and test if it even works on windows, I have no idea whether `memcmp` is available on Windows, otherwise I bet there is something comparable and we will have to conditionally choose the right testing facility or, in the worst case, warn and skip the test.

### CODE REVIEW

**Comment by unXedDani** [comment]
I'll add some more test even though I think they will run just fine. But I've been messing with writing the RLE-data decompressor in C++ So it be nice to be able to verify the Lua and C++ version match. This is mostly for Android and iOS where you don't jit the code.

Only 3 and 4 channel data is allowed right now. If we want to support more/less channels then we would need to know where to put it, LOVE imageData is only 4 channels. Grayscale seems easy enough but also kind of pointless if we where to use 4 channels for it.

memcmp is Standard library C function and should work everywhere.
I have no idea why my `user.name` is different. I'm doing all github work from one machine. I've never changed it anywhere.

Also make sure to not call the one argument version of `artal.newPSD(filename)` in the test-cases. They're threaded and because `artal.newPSD(filename)` calls `love.graphics,newImage()` it locks up for me on Windows.
I'm wondering if it was a good design choice to have layer data be loaded through `artal.newPSD(filedata, number)`. Perhaps something like `artal.newPSDLayer(filedata, number)`?

I also added you as a collaborator so you can push test code yourself.

**Comment by s-ol** [comment]
I guess then the user.name part comes from uploading and editing on github (dot com).

Yes, i think the interface should be changed but I'm not sure what would be the best way, maybe 

```
artal.loadDocument(name)
artal.loadDocument(name, false) -- no imagedata

artal.loadLayer(name, i)
artal.loadLayer(name, i, false) -- no imagedata
```

IMO there's rarely a reason to load only a single layer though. It might make more sense to somehow provide access to the "intermediate API" that is forming on my rewrite (readHeader, readLayers etc).

**Comment by s-ol** [comment]
Also now that you mention it, I'm surprised the .newImage thing doesn't happen on linux apparently. newImageData should be fine though, right?

**Comment by unXedDani** [comment]
The reason single layer loading is in Artal is so you can parse the psd structure, then selectively load the layers you want. The "Loading specific layers." sample on the front page shows this.

As for "intermediate API" I don't quite know what you mean. But if you want to expose the internal structure of the psd. Then I don't think it a great idea. Mostly because there is so much "noise" in the spec that is filtered out when the user gets the psd structure.

I like those names. Much cleaner than current API.
The love.graphics and love.window modules is not available from threads. So `love.image.newImageData()` works.

**Comment by s-ol** [comment]
hey @unXedDani, yesterday I pulled out this project again and resumed working on my rewrite (https://github.com/s-ol/artal/tree/rewrite) - it just passed the (small) test suite completely the first time!

There are some things missing still, like merging the global alpha channel, disabling image creation etc., and there will surely be some bugs I didn't find yet but I'm quite hapy with how readable the source is - but maybe that's just because i've been deep in it again :P

**Comment by EvineDev** [comment]
Hey,

That is looking good, I'll have a closer look when I have time. :+1:

**Pull request merged**
